version: '3.8'
services:
  frontend:
    image: pdf-to-audio-frontend
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: your-backend-image
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
