# Используем официальный образ Node.js для сборки Angular-приложения
FROM node:18 as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration production

# Используем официальный образ Nginx для запуска приложения
FROM nginx:alpine
COPY --from=build /app/dist/pdf-to-audio-frontend /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
